const DATA_FOR_CARDS = [
  [{ nameCategory: 'categories' },
    {
      word: 'Animals',
      translation: 'Животные',
      image: 'assets/images/categories/animals.jpg',
      audioSrc: '',
    },
    {
      word: 'Clothes',
      translation: 'Одежда',
      image: 'assets/images/categories/clothes.jpg',
      audioSrc: '',
    },

    {
      word: 'Occupations',
      translation: 'Профессии',
      image: 'assets/images/categories/occupations.jpg',
      audioSrc: '',
    },
    {
      word: 'Places',
      translation: 'Места',
      image: 'assets/images/categories/places.jpg',
      audioSrc: '',
    },
    {
      word: 'Space',
      translation: 'Космос',
      image: 'assets/images/categories/space.jpg',
      audioSrc: '',
    },
    {
      word: 'Transport',
      translation: 'Транспорт',
      image: 'assets/images/categories/transport.jpg',
      audioSrc: '',
    },
    {
      word: 'Vegetables',
      translation: 'Овощи',
      image: 'assets/images/categories/vegetables.jpg',
      audioSrc: '',
    },
    {
      word: 'Clothes',
      translation: 'Одежда',
      image: 'assets/images/categories/weather.jpg',
      audioSrc: '',
    }],
  [{ nameCategory: 'animals' },
    {
      word: 'cat',
      translation: 'кот',
      image: 'assets/images/animals/cat.jpg',
      audioSrc: 'assets/audio/animals/cat.mp3',
    },
    {
      word: 'cow',
      translation: 'корова',
      image: 'assets/images/animals/cow.jpg',
      audioSrc: 'assets/audio/animals/cow.mp3',
    },
    {
      word: 'deer',
      translation: 'олень',
      image: 'assets/images/animals/deer.jpg',
      audioSrc: 'assets/audio/animals/deer.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'assets/images/animals/dog.jpg',
      audioSrc: 'assets/audio/animals/dog.mp3',
    },
    {
      word: 'hippo',
      translation: 'бегемот',
      image: 'assets/images/animals/hippo.jpg',
      audioSrc: 'assets/audio/animals/hippo.mp3',
    },
    {
      word: 'kangaroo',
      translation: 'кенгуру',
      image: 'assets/images/animals/kangaroo.jpg',
      audioSrc: 'assets/audio/animals/kangaroo.mp3',
    },
    {
      word: 'koala',
      translation: 'коала',
      image: 'assets/images/animals/koala.jpg',
      audioSrc: 'assets/audio/animals/koala.mp3',
    },
    {
      word: 'monkey',
      translation: 'обезьяна',
      image: 'assets/images/animals/monkey.jpg',
      audioSrc: 'assets/audio/animals/monkey.mp3',
    },
    {
      word: 'moose',
      translation: 'лось',
      image: 'assets/images/animals/moose.jpg',
      audioSrc: 'assets/audio/animals/moose.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: 'assets/images/animals/mouse.jpg',
      audioSrc: 'assets/audio/animals/mouse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'assets/images/animals/pig.jpg',
      audioSrc: 'assets/audio/animals/pig.mp3',
    },
    {
      word: 'seal',
      translation: 'тюлень',
      image: 'assets/images/animals/seal.jpg',
      audioSrc: 'assets/audio/animals/seal.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'assets/images/animals/sheep.jpg',
      audioSrc: 'assets/audio/animals/sheep.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: 'assets/images/animals/turtle.jpg',
      audioSrc: 'assets/audio/animals/turtle.mp3',
    },
    {
      word: 'walrus',
      translation: 'морж',
      image: 'assets/images/animals/walrus.jpg',
      audioSrc: 'assets/audio/animals/walrus.mp3',
    }],
  [{ nameCategory: 'clothes' },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/images/clothes/blouse.jpg',
      audioSrc: 'assets/audio/clothes/blouse.mp3',
    },
    {
      word: 'cap',
      translation: 'кепка',
      image: 'assets/images/clothes/cap.jpg',
      audioSrc: 'assets/audio/clothes/cap.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'assets/images/clothes/dress.jpg',
      audioSrc: 'assets/audio/clothes/dress.mp3',
    },
    {
      word: 'gloves',
      translation: 'перчатки',
      image: 'assets/images/clothes/gloves.jpg',
      audioSrc: 'assets/audio/clothes/gloves.mp3',
    },
    {
      word: 'hoodie',
      translation: 'худи',
      image: './assets/images/clothes/hoodie.jpg',
      audioSrc: './assets/audio/clothes/hoodie.mp3',
    },
    {
      word: 'mittens',
      translation: 'рукавицы',
      image: './assets/images/clothes/mittens.jpg',
      audioSrc: './assets/audio/clothes/mittens.mp3',
    },
    {
      word: 'sandals',
      translation: 'сандали',
      image: 'assets/images/clothes/sandals.jpg',
      audioSrc: 'assets/audio/clothes/sandals.mp3',
    },
    {
      word: 'scarf',
      translation: 'шарф',
      image: 'assets/images/clothes/scarf.jpg',
      audioSrc: 'assets/audio/clothes/scarf.mp3',
    },
    {
      word: 'shoes',
      translation: 'туфли',
      image: 'assets/images/clothes/shoes.jpg',
      audioSrc: 'assets/audio/clothes/shoes.mp3',
    },
    {
      word: 'shorts',
      translation: 'шорты',
      image: 'assets/images/clothes/shorts.jpg',
      audioSrc: 'assets/audio/clothes/shorts.mp3',
    },
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'assets/images/clothes/skirt.jpg',
      audioSrc: 'assets/audio/clothes/skirt.mp3',
    },
    {
      word: 'slippers',
      translation: 'тапочик',
      image: 'assets/images/clothes/slippers.jpg',
      audioSrc: 'assets/audio/clothes/slippers.mp3',
    },
    {
      word: 'sneaker',
      translation: 'кроссовки',
      image: 'assets/images/clothes/sneaker.jpg',
      audioSrc: 'assets/audio/clothes/sneaker.mp3',
    },
    {
      word: 'suit',
      translation: 'костюм',
      image: 'assets/images/clothes/suit.jpg',
      audioSrc: 'assets/audio/clothes/suit.mp3',
    },
    {
      word: 'sweater',
      translation: 'свитер',
      image: 'assets/images/clothes/sweater.jpg',
      audioSrc: 'assets/audio/clothes/sweater.mp3',
    }],
  [{ nameCategory: 'occupations' },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'assets/images/clothes/blouse.jpg',
      audioSrc: 'assets/audio/clothes/blouse.mp3',
    },
  ]];

export default DATA_FOR_CARDS;
